yolo_model:

  config_file:
    name: robotyolo.cfg
  weight_file:
    name: robotyolo.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - robot
      - blind_robot
      - space_man
