subscribers:

  camera_reading:
    topic: /robot2/camera/rgb/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /robot2/check_for_objects

publishers:

  object_detector:
    topic: /robot2/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /robot2/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /robot2/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
