observation_sources: scan distance_sensors distance_sensors_clearing

scan: {sensor_frame: robot1/base_link, data_type: LaserScan, topic: robot1/scan, marking: true, clearing: true}
distance_sensors: {sensor_frame: robot1/base_link, data_type: PointCloud, topic: distance_sensors, marking: true, clearing: false, obstacle_range: 0.4, raytrace_range: 0.4, observation_persistence: 5.0 }
distance_sensors_clearing: {sensor_frame: robot1/base_link, data_type: PointCloud, topic: distance_sensors_clearing, marking: false, clearing: true, raytrace_range: 5.0, observation_persistence: 0.0 }

global_costmap: {
  global_frame: robot1/map,
  robot_base_frame: robot1/base_link,
}

local_costmap: {
  global_frame: robot1/odom,
  robot_base_frame: robot1/base_link,
}