observation_sources: scan distance_sensors

scan: {sensor_frame: robot1/hokuyo_link, data_type: LaserScan, topic: robot1/scan, marking: true, clearing: true}
distance_sensors: {sensor_frame: robot1/base_link, data_type: PointCloud2, topic: robot1/camera/depth/points, marking: true, clearing: false, obstacle_range: 0.4, raytrace_range: 0.4, observation_persistence: 5.0 }

global_costmap: {
  global_frame: robot1/map,
  robot_base_frame: robot1/base_link,
}

local_costmap: {
  global_frame: robot1/odom,
  robot_base_frame: robot1/base_link,
}