global_costmap: {
  update_frequency: 5.0,
  static_map: true 
}

local_costmap: {
  update_frequency: 5.0,
  publish_frequency: 2.0,
  static_map: false,
  rolling_window: true,
  width: 5.0,
  height: 5.0,
  resolution: 0.05 
}